module.exports = {
    Recommendation: {
        Priority: 'Urgent|Regular',
        RiskCharacterization: 'mission|accountability|information|life / health|penalties|reputation|wasted resources|lost benefits|operations|compliance',
        RiskEvaluation: 'State|Region|Municipality|Sector|Entity',
        Importance: 'Strategic|Important, but not essential',
        ImplementationStatus: 'I zbatuar|Pjesërisht i zbatuar|Nuk ka filluar zbatimi|Nuk është adresuar|Nuk është i aplikueshëm më|Pjesërisht nuk është i aplikueshëm më|Nuk ka filluar vlerësimi',
        Repeated: 'New reccomendation (A)|Repeated reccomendation (B)|Partialy repeated Reccomendation (C)|In Process (D)|Solved (E)|New status (F)'
    },
    NodeAttributes:{
        Priority: 'priority',
        RiskCharacterization: 'risk',
        RiskEvaluation: 'riskevaluation',
        Importance: 'importance',
        ImplementationStatus: 'status',
        Repeated: 'repeated'
    },
    weblang: {
        en:{
            main:{
                country:'REPUBLIC OF KOSOVO',
                sai:'NATIONAL AUDIT OFFICE',
                module:'Recommendations tracking system',
                update:'Last update',
                introduction:'The audits are presented as "collections", aggregated by type, subject, chronological milestones and their recommendations, along with related findings can be tracked and monitored here.',
                note1: 'Note',
                note2:'Only the audits published and authorized by the KNAO are available in the web version.',
                portfolio_subject:'Covers',
                portfolio_sai:'SAI',
                externallinks:'External Related Links',
                noaudits:'No audits available!',
                number: 'Number',
                search: 'Search',
                searchresults: 'Search results',
                numberresults:'$$$ Recommendation(s) were found. The results are ordered by relevance.',
                noteresults: 'In order to avoid excessive consumption of system resources only the first 100 results were retrieved. Try to be more specific in the search criteria!',
                presentin:'Present in: ',
                noresults: 'The search did not return recommendations!'
            },
            search: {
                introduction: 'Search tool on audit recommendations',
                note1: 'Note',
                note2: 'Type the search terms in the text box or combine them with the advanced options and press the search button',
                button: 'Search',
                option1: 'Any word',
                option2: 'Exact match',
                priority: 'By priority',
                riskareas: 'By risk area',
                rectype: 'By level',
                recimportance: 'By importance',
                status: 'By implementation status',
                repeated: 'Repeated?',
                advanced: 'Advanced options',
                ShowRec:'More information...',
                HideRec:'Less information'
            },
            portfolio:{
                rectstatus:'Global Recommendations Status',
                newissues: 'New Issues',
                riskareas: 'Risk areas identified'
            },
            audit:{
                recprogress: 'Progress of recommendations',
                priority: 'Priority',
                riskareas: 'Risk areas identified',
                rectype: 'Recommendations by type',
                recimportance: 'Importance of recommendations',
                status: 'Status (overall)',
                repeated: 'Repeated?',
                tabreccol1: 'Recommendation',
                tabreccol2: 'Priority',
                tabreccol3: 'Area',
                tabreccol4: 'Level',
                tabreccol5: 'Timeline',
                tabreccol6: 'Status',
                audit: 'Audit',
                year: 'year',
                background: 'Audit background',
                scope: 'Audit scope',
                importance: 'Strategic',
                priority: 'Urgent',
                report: 'Published report'
            },
            Recommendation: {
                Priority: 'Urgent|Regular',
                RiskCharacterization: 'mission|accountability|information|life / health|penalties|reputation|wasted resources|lost benefits|operations|compliance',
                RiskEvaluation: 'State|Region|Municipality|Sector|Entity',
                Importance: 'Strategic|Important, but not essential',
                ImplementationStatus: 'Implemented|Partially implemented|Not started Implementation|Not addressed|No longer applicable|Partially no longer applicable|Assessment has not started yet',
                Repeated: 'New reccomendation (A)|Repeated reccomendation (B)|Partialy repeated Reccomendation (C)|In Process (D)|Solved (E)|New status (F)'
            }

        },
        sq:{
            main:{
                country:'REPUBLIKA E KOSOVËS',
                sai:'ZYRA KOMBËTARE E AUDITIMIT',
                module:'Sistemi i vëzhgimit të rekomandimeve',
                update:'Përditësimi i fundit',
                introduction:'Auditimet paraqiten si "koleksione", të grupuara sipas llojit, entitetit, periudhave audituese dhe rekomandimet e tyre, dhe të tillat mund të gjurmohen dhe monitorohen këtu.',
                note1: 'Shënim',
                note2:'Vetëm auditimet e publikuara dhe të autorizuara nga ZKA janë në dispozicion në versionin në internet.',
                portfolio_subject:'Përfshinë',
                portfolio_sai:'ISA',
                externallinks:'Lidhje të jashtme',
                noaudits:'Nuk ka auditime të disponueshme!',
                number: 'Numri',
                search: 'Kërko',
                searchresults: 'Rezultatet e kërkimit',
                numberresults:'U gjetën $$$ rekomandime. Rezultatet renditen sipas rëndësisë.',
                noteresults: 'Për të shmangur konsumin e tepërt të burimeve të sistemit, paraqiten vetëm 100 rezultatet e para. Përpiquni të jeni më specifik në kriteret e kërkimit!',
                presentin:'Të pranishëm në: ',
                noresults: 'Kërkimi nuk gjeti rekomandime!'
            },
            search: {
                introduction: 'Mjet kërkimi për rekomandimet e auditimit',
                note1: 'Shënim',
                note2: 'Shënoni kushtet e kërkimit në kutinë e tekstit ose kombinoni ato me mundësitë e përparuara dhe shtypni butonin e kërkimit',
                button: 'Kërko',
                option1: 'Çdo fjalë',
                option2: 'Përputhja e saktë',
                priority: 'Sipas prioritetit',
                riskareas: 'Sipas fushës së rrezikut',
                rectype: 'Sipas llojit',
                recimportance: 'Nga rëndësia',
                status: 'Sipas statusit të zbatimit',
                repeated: 'Përsëritet?',
                advanced: 'Opsione te avancuara',
                ShowRec:'Më shumë informacion ...',
                HideRec:'Më pak informacion'
            },
            portfolio:{
                rectstatus:'Statusi i të gjitha rekomandimeve',
                newissues: 'Çështje të reja',
                riskareas: 'Fushat e identifikuara të rreziqeve'
            },
            audit:{
                recprogress: 'Progresi i rekomandimeve',
                priority: 'Prioriteti',
                riskareas: 'Fushat e identifikuara të rreziqeve',
                rectype: 'Rekomandimet sipas llojit',
                recimportance: 'Rëndësia e rekomandimeve',
                status: 'Statusi (i përgjithshëm)',
                repeated: 'Përsëritet?',
                tabreccol1: 'Rekomandimi',
                tabreccol2: 'Prioriteti',
                tabreccol3: 'Zona',
                tabreccol4: 'Niveli',
                tabreccol5: 'Afati kohor',
                tabreccol6: 'Statusi',
                audit: 'Auditimi',
                year: 'viti',
                background: 'Qëllimi i auditimit',
                scope: 'Fushëveprimi i auditimit',
                importance: 'Strategjik',
                priority: 'Urgjent',
                report: 'Raporti i publikuar'
            },
            Recommendation: {
                Priority: 'Urgjent|I rregullt',
                RiskCharacterization: 'misioni|llogaridhënia|informacioni|jeta /shëndeti|ndëshkimet|reputacioni|resurset e humbura|përfitimet e humbura|operacionet|pajtueshmëria',
                RiskEvaluation: 'Shteti|Regjioni|Komuna|Sektori|Entiteti',
                Importance: 'Strategjik|I rëndësishëm, por jo thelbësor',
                ImplementationStatus: 'I zbatuar|Pjesërisht i zbatuar|Nuk ka filluar zbatimi|Nuk është adresuar|Nuk është i aplikueshëm më|Pjesërisht nuk është i aplikueshëm më|Nuk ka filluar vlerësimi',
                Repeated: 'Rekomandimet e reja (A)|Rekomandimet e përsëritura (B)|Rekomandimet pjesërisht të përsëritura (C)|Në proçes (D)|Zgjidhur (E)|Statusi i ri (F)'
            }
        },
        sr:{
            main:{
                country:'REPUBLIKA KOSOVO',
                sai:'NACIONALNA KANCELARIJA REVIZIJE',
                module:'Sistem praćenja preporuka',
                update:'Poslednje ažuriranje',
                introduction:'Revizije su predstavljene kao „zbirke“, objedinjene prema tipu, predmetu, hronološkim prekretnicama i njihovim preporukama, zajedno sa srodnim nalazima mogu se pratiti i nadgledati ovde.',
                note1: 'Beleška',
                note2:'Samo revizije objavljene i odobrene od strane NKRK su dostupne u veb verziji.',
                portfolio_subject:'Obuhvata',
                portfolio_sai:'VRI',
                externallinks:'Spoljne srodne veze',
                noaudits:'Revizije nisu dostupne!',
                number: 'Broj',
                search: 'Pretraga',
                searchresults: 'Rezultati pretrage',
                numberresults:'Pronađene su $$$ preporuke. Rezultati su poređani po važnosti.',
                noteresults: 'Da bi se izbegla prekomerna potrošnja sistemskih resursa, pronađeno je samo prvih 100 rezultata. Pokušajte da budete precizniji u kriterijumima pretrage!',
                presentin:'Prisutno na: ',
                noresults: 'Pretraga nije vratila preporuke!'
            },
            search: {
                introduction: 'Alat za pretragu po preporukama revizije',
                note1: 'Beleška',
                note2: 'Unesite pojmove za pretragu u okvir za tekst ili ih kombinirajte sa naprednim opcijama i pritisnite dugme za pretragu',
                button: 'Pretraga',
                option1: 'Bilo koja reč',
                option2: 'Tačno poklapanje',
                priority: 'Prema prioritetu',
                riskareas: 'Prema rizičnom području',
                rectype: 'Prema nivou',
                recimportance: 'Prema važnosti',
                status: 'Prema statusu primene',
                repeated: 'Ponovljeno?',
                advanced: 'Napredne opcije',
                ShowRec:'Više informacija ...',
                HideRec:'Manje informacija'
            },
            portfolio:{
                rectstatus:'Status globalnih preporuka',
                newissues: 'Nova izdanja',
                riskareas: 'Utvrđena područja rizika'
            },
            audit:{
                recprogress: 'Napredak preporuka',
                priority: 'Prioritet',
                riskareas: 'Utvrđena područja rizika',
                rectype: 'Preporuke prema tipu',
                recimportance: 'Značaj preporuka',
                status: 'Status (sveukupno)',
                repeated: 'Ponovljeno?',
                tabreccol1: 'Preporuka',
                tabreccol2: 'Prioritet',
                tabreccol3: 'Područje',
                tabreccol4: 'Nivo',
                tabreccol5: 'Vremenska linija',
                tabreccol6: 'Status',
                audit: 'Revizija',
                year: 'godina',
                background: 'Pozadina revizije',
                scope: 'Delokrug revizije',
                importance: 'Strateški',
                priority: 'Hitno',
                report: 'Objavljen izveštaj'
            },
            Recommendation: {
                Priority: 'Hitno|Redovno',
                RiskCharacterization: 'misija|odgovornost|informacije|život / zdravlje|kazne|reputacija|rasipanje resursa|izgubljene koristi|operacije|usklađenost',
                RiskEvaluation: 'Država|Regija|Opština|Sektor|Entitet',
                Importance: 'Strateški|Važno, ali ne i suštinski',
                ImplementationStatus: 'Sproveden|Delimično sproveden|Nije počela primena|Nije adresirana|Nije više primenljiv|Delimično nije više primenljiv|Assessment has not started yet',
                Repeated: 'Nova Preporuka (A)|Ponovljena Preporuka (B)|Delomično ponovljene preporuke (C)|U procesu (D)|Rešeno (E)|Novi status (F)'
            }
        }
    }
};